server:
  port: ${SERVER_PORT:8080}
spring:
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/university
    username: postgres
    password: rfnfdfcbz123!
  jpa:
    hibernate:
      ddl-auto: update