server:
  port: ${SERVER_PORT:8082}
logging:
  level:
    org.springframework.security: TRACE
spring:
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/university
    username: postgres
    password: rfnfdfcbz123!
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/eselpo
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/eselpo
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: springsecurity
            client-secret: fqIYtltRkPDnFv01NEPePlM2av68XMFd
            scope: openid
## Prometheus
management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metric # Включить конечные точки Prometheus
  metrics:
    export:
      prometheus:
        enabled: true # Включить экспорт prometheus
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true # включить гистограмму на основе процентилей для http запросов
      sla:
        http:
          server:
            requests: 100 мс, 150 мс, 250 мс, 500 мс, 1 с
    enable:
      jvm: true