insert into subject(id, name ,description) values
(1,'Introduction to Computational Science and Engineering','Follows the same pedagogy as 6.0002 (Introduction to Computational Thinking and Data Science), including Python, but is set in the context of computational science and engineering and uses applications from across science and engineering including dynamics, mechanics, robotics, heat transfer, climate science, chemistry, biology, aerospace and others.

This course provides an introduction to computational algorithms for understanding of scientific phenomena and designing of engineering systems. Topics include: computational algorithms to simulate time-dependent phenomena; optimize and control applications from science and engineering; and quantify uncertainty in problems involving randomness, including an introduction to probability and statistics.

Credit cannot also be received for 6.0002. Can be combined with 6.0001 (Introduction to Computer Science Programming in Python) for REST credit.'),
(2,'Linear Algebra and Optimization','Covers same fundamental concepts as 18.06 with a view toward modeling, computation, and applications. Integrates geometric, algebraic, and computational viewpoints.

Unified introduction to linear algebra and optimization, their interconnections, and applications throughout science and engineering. Topics include: vectors, matrices, eigenvalues, singular values, least-squares, convex optimization, linear/quadratic programming, gradient descent, Newton’s method. Viewpoint will emphasize conceptual, geometric, and computational aspects. Applications from many domains, including networks, signal processing, and machine learning.

Approved substitution for 18.06 for EECS and Math students.'),
(3,'Modeling with Machine Learning','Teaches students from a range of majors to translate a problem into a machine learning (ML) formulation and find appropriate tools for solving it. Students enroll in two 6-unit modules, run in tandem over the course of a full term—the common core, which covers ML fundamentals, and one of four discipline-specific modules that build on the core material.'),
(4,'Core Module','Focuses on modeling with machine learning methods with an eye towards applications in engineering and sciences. Students will be introduced to modern machine learning methods, from supervised to unsupervised models, with an emphasis on newer neural approaches. Develops understanding of how and why the methods work from the point of view of modeling, and when they are applicable. Using concrete examples, covers formulation of machine learning tasks, adapting and extending methods to given problems, and how the methods can and should be evaluated. Students taking graduate version complete additional assignments. Enrollment limited.'),
(5,'Programming Skills and Computational Thinking in-Context','Teaches experimental section of 6.0001 (Introduction to Computer Science and Programming in Python) in tandem with the Physics I GIR. In the fall term, one section of ES.801 (ESG version of 8.01, 12 units) is paired with one section of 6.0001 (6 units). Students in these sections will enroll in both subjects and receive separate course grades for each subject. This pilot will generate a library of problems that connect and combine basic computation in Python with basic concepts in the physics GIRs.'),
(6,'Nanoelectronics and Computing Systems','Studies interaction between materials, semiconductor physics, electronic devices, and computing systems. Develops intuition of how transistors operate. Topics range from introductory semiconductor physics to modern state-of-the-art nano-scale devices. Considers how innovations in devices have driven historical progress in computing, and explores ideas for further improvements in devices and computing. Students apply material to understand how building improved computing systems requires knowledge of devices, and how making the correct device requires knowledge of computing systems. Includes a design project for practical application of concepts, and labs for experience building silicon transistors and devices.'),
(7,'Fundamentals of Programming','Introduces fundamental concepts of programming. Designed to develop skills in applying basic methods from programming languages to abstract problems. Topics include programming and Python basics, computational concepts, software engineering, algorithmic techniques, data types, and recursion.  Lab component consists of software design, construction, and implementation of design. Enrollment may be limited.');

